cache:
  key: ${CI_COMMIT_REF_SLUG}

variables:
  GIT_SUBMODULE_STRATEGY: normal

debug-gcc:
  image: gitlab.ae.cs.uni-frankfurt.de:5001/ae-ci/aeffm-gcc
  stage: test
  script:
    - mkdir build; cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-9 -DCMAKE_CXX_FLAGS="-Werror" -DZERO_NODE_ASSERT=On -GNinja ..
    - ninja
    - ctest
    - cd bin; echo "disk=,memory,1G" > .stxxl; ../../py/run-tests.py

release-gcc:
  image: gitlab.ae.cs.uni-frankfurt.de:5001/ae-ci/aeffm-gcc
  stage: test
  script:
    - mkdir build; cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-9 -DCMAKE_CXX_FLAGS="-Werror" -GNinja ..
    - ninja
    - ctest
    - cd bin; echo "disk=,memory,1G" > .stxxl;  ../../py/run-tests.py
